export const comprehensiveICSExamples = [
  {
    name: "Basic Meeting with Core Properties",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CleanCorp//Meeting Scheduler//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:meeting001@cleancorp.com
DTSTART:20250915T090000Z
DTEND:20250915T100000Z
DTSTAMP:20250914T180000Z
SUMMARY:Team Standup Meeting
DESCRIPTION:Weekly team standup to discuss progress and blockers
LOCATION:Conference Room A, 123 Business St
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
PRIORITY:5
CREATED:20250901T120000Z
LAST-MODIFIED:20250914T180000Z
SEQUENCE:1
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Event with Geographic Coordinates",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//LocationTracker//GPS Events//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:gps001@locationtracker.com
DTSTART:20250916T140000Z
DTEND:20250916T160000Z
DTSTAMP:20250915T180000Z
SUMMARY:Outdoor Team Building
DESCRIPTION:Annual outdoor team building activities
LOCATION:Central Park, New York
GEO:40.785091;-73.968285
STATUS:TENTATIVE
CLASS:PUBLIC
CATEGORIES:TEAM,OUTDOOR,SOCIAL
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Recurring Event with Complex Recurrence Rule",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//RecurringEvents//Scheduler//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:recurring001@scheduler.com
DTSTART:20250917T090000Z
DTEND:20250917T093000Z
DTSTAMP:20250916T180000Z
SUMMARY:Daily Standup
DESCRIPTION:Daily standup meeting for development team
LOCATION:Virtual - Zoom Room 123
RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR;UNTIL=20251031T235959Z
EXDATE:20250925T090000Z,20251013T090000Z,20251014T090000Z
STATUS:CONFIRMED
CLASS:CONFIDENTIAL
PRIORITY:7
CATEGORIES:WORK,MEETING,DEVELOPMENT
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Event with Multiple Attendees and Full Details",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AttendeeManager//Corporate//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
UID:corporate001@attendeemanager.com
DTSTART:20250918T140000Z
DTEND:20250918T160000Z
DTSTAMP:20250917T180000Z
SUMMARY:Quarterly Review Meeting
DESCRIPTION:Q3 2025 quarterly business review and planning session
LOCATION:Executive Conference Room, 45th Floor
ORGANIZER;CN=John Manager;DIR="ldap://directory.company.com/cn=John%20Manager":mailto:john@company.com
ATTENDEE;CN=Sarah Smith;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CUTYPE=INDIVIDUAL:mailto:sarah@company.com
ATTENDEE;CN=Mike Johnson;ROLE=OPT-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=FALSE;CUTYPE=INDIVIDUAL:mailto:mike@company.com
ATTENDEE;CN=Lisa Wong;ROLE=REQ-PARTICIPANT;PARTSTAT=TENTATIVE;RSVP=TRUE;CUTYPE=INDIVIDUAL;DELEGATED-FROM="mailto:bob@company.com":mailto:lisa@company.com
CONTACT:john@company.com
STATUS:CONFIRMED
CLASS:PRIVATE
TRANSP:OPAQUE
PRIORITY:9
CATEGORIES:BUSINESS,QUARTERLY,REVIEW
RESOURCES:PROJECTOR,WHITEBOARD,CATERING
URL:https://company.com/meetings/q3-review
SEQUENCE:2
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Event with Multiple Alarms",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AlarmSystem//Notifications//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:alarms001@alarmsystem.com
DTSTART:20250919T190000Z
DTEND:20250919T210000Z
DTSTAMP:20250918T180000Z
SUMMARY:Important Client Dinner
DESCRIPTION:Dinner meeting with potential major client
LOCATION:Le Bernardin, 155 W 51st St, New York, NY
STATUS:CONFIRMED
CLASS:CONFIDENTIAL
PRIORITY:8
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Client dinner in 1 hour
TRIGGER:-PT1H
END:VALARM
BEGIN:VALARM
ACTION:EMAIL
DESCRIPTION:Client dinner reminder
SUMMARY:Don't forget client dinner tonight!
TRIGGER:-PT2H
ATTENDEE:mailto:manager@company.com
END:VALARM
BEGIN:VALARM
ACTION:AUDIO
TRIGGER:-PT15M
ATTACH:FMTTYPE=audio/wav:http://company.com/sounds/urgent.wav
REPEAT:3
DURATION:PT5M
END:VALARM
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "To-Do Task with Completion Tracking",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//TaskManager//ToDo//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTODO
UID:task001@taskmanager.com
DTSTART:20250920T090000Z
DUE:20250925T170000Z
DTSTAMP:20250919T180000Z
SUMMARY:Complete Q3 Budget Report
DESCRIPTION:Finalize and submit the quarterly budget report to finance department
PRIORITY:6
STATUS:IN-PROCESS
PERCENT-COMPLETE:75
CATEGORIES:WORK,FINANCE,REPORT
ORGANIZER;CN=Finance Manager:mailto:finance@company.com
RELATED-TO:budget-cycle-2025@company.com
COMPLETED:20250924T160000Z
SEQUENCE:3
END:VTODO
END:VCALENDAR`
  },
  
  {
    name: "Journal Entry",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PersonalJournal//Diary//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VJOURNAL
UID:journal001@personaljournal.com
DTSTART:20250922T220000Z
DTSTAMP:20250922T220000Z
SUMMARY:Daily Reflection
DESCRIPTION:Today was highly productive. Completed the client presentation and received positive feedback. Team collaboration was excellent during the morning standup. Looking forward to tomorrow's new project kickoff.
CATEGORIES:PERSONAL,REFLECTION,WORK
CLASS:PRIVATE
STATUS:FINAL
CREATED:20250922T220000Z
LAST-MODIFIED:20250922T220000Z
SEQUENCE:1
END:VJOURNAL
END:VCALENDAR`
  },
  
  {
    name: "Free/Busy Time Periods",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//SchedulingSystem//FreeBusy//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VFREEBUSY
UID:freebusy001@schedulingsystem.com
DTSTART:20250923T080000Z
DTEND:20250923T180000Z
DTSTAMP:20250922T180000Z
ORGANIZER;CN=John Scheduler:mailto:john@company.com
FREEBUSY;FBTYPE=BUSY:20250923T090000Z/20250923T100000Z
FREEBUSY;FBTYPE=BUSY:20250923T140000Z/20250923T160000Z
FREEBUSY;FBTYPE=TENTATIVE:20250923T110000Z/20250923T120000Z
FREEBUSY;FBTYPE=FREE:20250923T080000Z/20250923T090000Z
CONTACT:scheduler@company.com
URL:https://company.com/calendar/freebusy/john
END:VFREEBUSY
END:VCALENDAR`
  },
  
  {
    name: "Event with Custom Properties",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CustomCorp//Extended Properties//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:custom001@customcorp.com
DTSTART:20250924T130000Z
DTEND:20250924T143000Z
DTSTAMP:20250923T180000Z
SUMMARY:Product Launch Meeting
DESCRIPTION:Final preparations for product launch
LOCATION:Innovation Lab
STATUS:CONFIRMED
CLASS:PUBLIC
PRIORITY:8
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-CUSTOM-DEPARTMENT:Marketing
X-PROJECT-CODE:LAUNCH2025
X-BUDGET-CODE:MKT-Q3-001
X-ROOM-CAPACITY:25
X-CATERING-REQUIRED:TRUE
X-AV-EQUIPMENT:Projector,Microphone,Video Conference
CATEGORIES:PRODUCT,LAUNCH,MARKETING
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Multi-Day Event with Duration",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//EventPlanner//Multi-Day//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:multiday001@eventplanner.com
DTSTART:20250926T000000Z
DURATION:P3DT4H30M
DTSTAMP:20250925T180000Z
SUMMARY:Annual Company Retreat
DESCRIPTION:Three-day company retreat including team building, strategic planning, and social activities
LOCATION:Mountain Resort Lodge, Lake Tahoe
GEO:39.0968;-120.0324
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
PRIORITY:7
CATEGORIES:COMPANY,RETREAT,TEAM-BUILDING
RESOURCES:LODGE,ACTIVITIES,CATERING,TRANSPORTATION
CONTACT:events@company.com
URL:https://company.com/events/annual-retreat-2025
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Timezone-Specific Event",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//TimezoneEvents//Global//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:America/New_York
BEGIN:STANDARD
DTSTART:20251102T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20250309T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:timezone001@globalevent.com
DTSTART;TZID=America/New_York:20250930T140000
DTEND;TZID=America/New_York:20250930T153000
DTSTAMP:20250929T180000Z
SUMMARY:Global Team Sync
DESCRIPTION:Weekly sync with international team members
LOCATION:Virtual Meeting Room
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY;BYDAY=TU
CATEGORIES:GLOBAL,SYNC,VIRTUAL
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "Cancelled Event with History",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CancellationManager//Events//EN
CALSCALE:GREGORIAN
METHOD:CANCEL
BEGIN:VEVENT
UID:cancelled001@cancellation.com
DTSTART:20251001T160000Z
DTEND:20251001T170000Z
DTSTAMP:20251001T080000Z
SUMMARY:Client Presentation - CANCELLED
DESCRIPTION:Client presentation cancelled due to emergency. Will reschedule for next week.
LOCATION:Client Office, Downtown
STATUS:CANCELLED
CLASS:PUBLIC
PRIORITY:5
ORGANIZER;CN=Sales Manager:mailto:sales@company.com
ATTENDEE;CN=Client Rep;PARTSTAT=NEEDS-ACTION:mailto:client@clientcompany.com
CREATED:20250915T120000Z
LAST-MODIFIED:20251001T080000Z
SEQUENCE:5
CATEGORIES:SALES,CLIENT,PRESENTATION
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "High Priority Urgent Event",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//UrgentEvents//Crisis Management//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:urgent001@urgentevents.com
DTSTART:20251008T153000Z
DTEND:20251008T163000Z
DTSTAMP:20251008T153000Z
SUMMARY:URGENT: System Outage Response
DESCRIPTION:Emergency response meeting for critical system outage. All hands on deck required.
LOCATION:Emergency Operations Center
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
PRIORITY:1
CATEGORIES:EMERGENCY,SYSTEM,OUTAGE,URGENT
ORGANIZER;CN=IT Director:mailto:it-director@company.com
ATTENDEE;CN=Dev Team Lead;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:dev-lead@company.com
ATTENDEE;CN=Ops Manager;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:ops@company.com
ATTENDEE;CN=Customer Success;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:support@company.com
RESOURCES:INCIDENT RESPONSE TOOLS,COMMUNICATION SYSTEMS
CONTACT:emergency@company.com
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:URGENT MEETING NOW
TRIGGER:PT0S
REPEAT:5
DURATION:PT2M
END:VALARM
END:VEVENT
END:VCALENDAR`
  },
  
  {
    name: "All-Day Event with Transparency",
    ics: `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AllDayEvents//Holiday Manager//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:allday001@alldayevents.com
DTSTART;VALUE=DATE:20251013
DTSTAMP:20251012T180000Z
SUMMARY:Company Holiday - Indigenous Peoples' Day
DESCRIPTION:Company-wide holiday observance. Offices closed.
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:TRANSPARENT
PRIORITY:5
CATEGORIES:HOLIDAY,COMPANY,OBSERVANCE
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-COMPANY-HOLIDAY-TYPE:FEDERAL
END:VEVENT
END:VCALENDAR`
  }
];